url: https://caccoalition.github.io/
baseurl: /agency-jekyll-theme/

# Site settings
title: Coalition Against Climate Change
email: coalitionagainstclimatechange@gmail.com
description: "We are a USA based nonprofit that seeks to raise awareness about climate change and create change that helps preserve our planet."


# Team names, titles and social links
people:
- name: Elaine Ly
  pic: 1
  position: Chief Executive Officer
  social:
    - title: instagram
      url: #
    - title: facebook
      url: #
    - title: twitter
      url: #

- name: Sanjay Nagaraj
  pic: 2
  position: Chief Technology Officer
  social:
    - title: facebook
      url: https://www.facebook.com/sanjayn2816
    - title: instagram
      url: https://www.instagram.com/sanjay_n1/
    - title: twitter
      url: https://twitter.com/SanjayNagaraj11

- name: Bailey Hirota
  pic: 3
  position: Chief Operating Officer
  social:
    - title: instagram
      url: #
    - title: facebook
      url: #
    - title: twitter
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
 # - title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
 # - title: bitbucket 
 #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/caccoalition/caccoalition.github.io

# Postal address (add as many lines as necessary)
#address:
  #- line: 3481 Melrose Place
 # - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
